language: r
sudo: required
warnings_are_errors: false
  
r_github_packages:
  - hadley/testthat
  - hadley/httr
  - jimhester/covr
  - yihui/knitr
  - jeroenooms/jsonlite
  - jeroenooms/curl

# https://github.com/travis-ci/travis-ci/issues/4125  
env:
  global:
    - NOT_CRAN=true
    
before_install: echo "options(repos = c(CRAN='http://cran.rstudio.com'))" > ~/.Rprofile
   
notifications:
  email:
    on_success: never
    on_failure: always
    
after_success:
  - Rscript -e 'library(covr);coveralls()'
