language: r
sudo: required
warnings_are_errors: false
  
r_github_packages:
  - hadley/testthat
  - hadley/httr
  - jimhester/covr
  - yihui/knitr
  - jeroenooms/curl
  - jeroenooms/jsonlite
  - s-u/PKI
  - hadley/secure

notifications:
  email:
    on_success: never
    on_failure: always
    
after_success:
  - Rscript -e 'library(covr);coveralls()'
  
env: 
  - secure: NrOlYooHM36qhMdBRMvLSlXb92pRaKYGAQA0NvJHtzEEHSLTdfG3co0ywQeF0UIOiQB3XQsekcQF8UcR3wKTgb1bMkQ8f/dGYy2wtUTGIs/nYdYoIoN8VFQsyKPp+Ic89D7pO/8nK1BSAfIU9vgNlDzWULstFhQT38pmXvuKZZwcCKVF3Z0S9HJxztsGRIxN6wtpLub8HPd1y8vdMq3kPtKB+2dUHmmHIsypL5+euCm59IRlIeFb9W9R7Ce9WNNaLjneXX+6O9KcbPfSU8xqaTUy4BO6SjxldiT2nvvaEdJMLeC2Rej0QzKFQsyxKORnTDXp5BT+B7v+h1yTJswfai+118DFdsR6A7kVCjzvZLENzHD0va2J8VvBNCDxMeUSRn/Rr3ZLlYcQUQpqiw4PaRfoIBfBiJF2nA+YHUC7WdG42q3ljYv5VUkCaBLViezfyb0bwV6i+lS6ZM4ouHkTAPLaOejqfZ5vgsNcr/EWtdwrggOYklR6AkGQ9UtbgbM/tiQlRiK4FsCt9ypF3cneDBfUI4to/z39hVUAEFrTWM+kSugcVnycppFLoXk9ojca6HIqMhi9yPeVlMNH2phv9WwvljknrZD6AJS2NbFN7/d5ciZGHu+aWEfDLzqJWY26L4fTnsObUcFvPRK4GXa1Wx9SXGT0U+790aME5LptjIY=