language: r
warnings_are_errors: false
  
r_github_packages:
  - hadley/testthat
  - hadley/httr
  - jimhester/covr
  - yihui/knitr
  - jeroenooms/curl
  - jeroenooms/jsonlite
  
notifications:
  email:
    on_success: never
    on_failure: always
    
after_success:
  - Rscript -e 'library(covr);coveralls()'