language: r
sudo: required
warnings_are_errors: true

r_github_packages:
  - hadley/testthat
  - hadley/httr
  - jimhester/covr
  - yihui/knitr
  - jeroenooms/curl
  - jeroenooms/jsonlite
  
after_success:
  - Rscript -e 'library(covr);coveralls()'