language: r
sudo: required
warnings_are_errors: true

r_github_packages:
  - rstudio/rmarkdown
  - hadley/testthat
  - jimhester/covr
  - yihui/knitr
  
after_success:
  - Rscript -e 'library(covr);coveralls()'